version: '3.7'

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/backend/web/static
      - media_volume:/home/backend/web/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
